#I. 우수초콜릿분석

##1. CSV를 읽어 배열로 반환하는 넘파이의 loadtxt( ) 함수를 사용하고 delimiter 인자로 데이터를 읽어올 때 구분 기호를 콤마(,)로 설정

In [4]:
import numpy as np
data = np.loadtxt('chocolate_ranking.csv', delimiter=',')

#빈칸 채우기
print('차원:', data.ndim)
print('모양:', data.shape)
print('원소 수:', data.size)
print(data)

차원: 2
모양: (1795, 4)
원소 수: 7180
[[1.000e+00 2.016e+03 6.300e-01 3.750e+00]
 [2.000e+00 2.015e+03 7.000e-01 2.750e+00]
 [3.000e+00 2.015e+03 7.000e-01 3.000e+00]
 ...
 [1.793e+03 2.011e+03 6.500e-01 3.500e+00]
 [1.794e+03 2.011e+03 6.200e-01 3.250e+00]
 [1.795e+03 2.010e+03 6.500e-01 3.000e+00]]


##2. 모든 초콜릿의 평균 평점을 알아보기. 슬라이싱한 넘파이 배열에 통계함수 mean( )을 사용

In [5]:
#빈칸 채우기
ratings_mean =  data[3].mean()
print(ratings_mean)

505.8


##3.평점이 4 이상인 우수 초콜릿을 high_level로 저장. 우수 초콜릿의 번호를 정수로 변환

In [6]:
#빈칸 채우기
high_level = data[:, 3] >= 4
# print(high_level)
high_id = data[high_level][:, 0].astype(int)
print('우수 초콜릿 수:', high_id.size)
print(high_id)
# print(high_level)

우수 초콜릿 수: 100
[  10   18   21   55   57   77   78   79   84   87   88   93  108  109
  118  124  153  180  181  187  223  232  233  240  243  244  245  248
  257  312  316  317  358  437  503  567  573  574  582  601  650  687
  690  691  701  720  730  800  828  862  864  865  866  883  919  993
 1088 1089 1118 1119 1120 1204 1241 1245 1247 1274 1277 1278 1289 1291
 1293 1295 1323 1331 1336 1378 1394 1426 1428 1433 1479 1488 1513 1516
 1529 1530 1531 1533 1536 1537 1544 1545 1664 1683 1686 1688 1694 1700
 1740 1757]


##4.우수 초콜릿의 카카오 함유량 빈도를 분석합니다. 넘파이의 unique( ) 함수는 배열에서 중복 값을 제거하여 남은 값의 배열과 빈도수를 반환

In [7]:
#빈칸 채우기
# high_kakao = high_id
high_kakao = data[high_level][:, 2]
# print(high_kakao)
unique_values, value_counts = np.unique(high_kakao, return_counts=True)
print('카카오 함유량:', unique_values)
print('함유량별 빈도수:', value_counts)

카카오 함유량: [0.6  0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75
 0.78 0.8  0.88]
함유량별 빈도수: [ 1  3  4  2  1  3  2  2 45  1 11  1  4 17  1  1  1]


##5.우수 초콜릿 중 가장 빈도수가 큰 카카오 함유량을 구함

In [8]:
#빈칸 채우
max_index = np.argmax(value_counts)
# print(max_index)
print(unique_values[max_index])
print('우수 초콜릿', high_id.size, '가지 중', value_counts[max_index],\
      '가지의 카카오 함유량이', unique_values[max_index] * 100, '%입니다.')

0.7
우수 초콜릿 100 가지 중 45 가지의 카카오 함유량이 70.0 %입니다.


#II.강의 시간표 분석

##1.열 이름과 시간표 데이터를 리스트로 저장

In [9]:
col_names = ['과목번호', '과목명', '강의실', '시간수']
list1 = list([['C1', '인공지능개론', 'R1', 3],
              ['C2', '웃음치료', 'R2', 2],
              ['C3', '경영학', 'R3', 3],
              ['C4', '3D디자인', 'R4', 4],
              ['C5', '스포츠경영', 'R2', 2],
              ['C6', '예술의 세계', 'R3', 1]])

##2.시간표 데이터를 데이터프레임 객체 df로 변환하여 CSV 파일로 저장

In [10]:
import pandas as pd
df = pd.DataFrame(list1, columns=col_names)
df.to_csv('./timetable.csv', header=True, index=False, encoding='utf-8')

##3.‘timetable.csv’ 파일을 데이터프레임 객체 df2로 읽고, 열 이름이 ‘교수’인 열을 추가. 값으로 ‘김예희’, ‘오정현’, ‘인세훈’, ‘이새봄’, ‘배유진’, ‘이가원’을 저장.

In [11]:
#빈칸 채우기
df2 = pd.read_csv('./timetable.csv', sep=',')

#열 이름이 ‘교수’인 열을 추가.
#값으로 ‘김예희’, ‘오정현’, ‘인세훈’, ‘이새봄’, ‘배유진’, ‘이가원’을 저장
##여기에 코드를 작성하시오
df2['교수'] = ['김예희', '오정현', '인세훈', '이새봄', '배유진', '이가원']

df2

과목번호     과목명 강의실  시간수   교수
0   C1  인공지능개론  R1    3  김예희
1   C2    웃음치료  R2    2  오정현
2   C3     경영학  R3    3  인세훈
3   C4   3D디자인  R4    4  이새봄
4   C5   스포츠경영  R2    2  배유진
5   C6  예술의 세계  R3    1  이가원

##4.강의실을 기준으로 그룹화하여 max( ) 함수로 최대 시간 수를 구하기.

In [12]:
max_hour = df2.groupby(by=['강의실'], as_index=False)['시간수'].max()
max_hour

강의실  시간수
0  R1    3
1  R2    2
2  R3    3
3  R4    4