#2.넘파이 활용

In [4]:
import numpy as np

#리스트를 생성하고 배열로 변환하기
list1 = [1, 2, 3, 4]
a = np.array(list1)
print('a.shape: ', a.shape)
print('a[0]: ', a[0])

a.shape:  (4,)
a[0]:  1


In [5]:
#2차원 배열 생성하기
b = np.array([[1, 2, 3], [4, 5, 6]])
print('b.shape: ', b.shape)
print('b[0,0]: ', b[0,0])
print('b[0]: ', b[0])

b.shape:  (2, 3)
b[0,0]:  1
b[0]:  [1 2 3]


In [6]:
a = np.zeros(2)
print('a\n', a)
b = np.zeros((2,2))
print('b\n', b)
c = np.ones((2,3))
print('c\n', c)
d = np.full((2,3), 5)
print('d\n', d)
e = np.eye(3)
print('e\n', e) 

a
 [0. 0.]
b
 [[0. 0.]
 [0. 0.]]
c
 [[1. 1. 1.]
 [1. 1. 1.]]
d
 [[5 5 5]
 [5 5 5]]
e
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#실수형 배열 생성하기
a = np.array([1, 2], dtype=np.float64)
print(a.dtype)
#정수형 배열로 변환하기
a_i8 = a.astype(np.int8)
print(a_i8.dtype)

float64
int8


In [8]:
arr = np.array([[0, 1, 2], [3, 4, 5]])
print('type(arr):',type(arr))
print('arr.ndim:',arr.ndim)
print('arr.dtype:',arr.dtype)
print('arr.itemsize:',arr.itemsize)
print('arr.size:',arr.size)
print('arr.nbytes:',arr.nbytes)
print('arr.T:\n',arr.T)
print('arr.shape:',arr.shape)

type(arr): <class 'numpy.ndarray'>
arr.ndim: 2
arr.dtype: int64
arr.itemsize: 8
arr.size: 6
arr.nbytes: 48
arr.T:
 [[0 3]
 [1 4]
 [2 5]]
arr.shape: (2, 3)


In [9]:
#1차원 배열 생성하기
a = np.arange(8)
print('a\n', a)
#다차원 배열로 변경하기
a.shape = (2,4)
print('shape\n', a)
#1차원 배열로 변경하기
print('flatten\n', a.flatten( ))
#resize 함수로 모양 변경하기
a.resize((4,2))
print('resize\n', a)

a
 [0 1 2 3 4 5 6 7]
shape
 [[0 1 2 3]
 [4 5 6 7]]
flatten
 [0 1 2 3 4 5 6 7]
resize
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [10]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print('a\n', a)
b = a.transpose( )
print('b\n', b)
c = a.T
print('c\n', c)

a
 [[0 1 2]
 [3 4 5]]
b
 [[0 3]
 [1 4]
 [2 5]]
c
 [[0 3]
 [1 4]
 [2 5]]


In [ ]:
mask = np.array([0, 1, 1, 0], dtype=bool)
print(mask)
data = np.random.randn(4,2)
print('\ndata 출력\n',data) #랜덤 데이터 배열 data는 책과 다르게 나타남
print('\n마스킹된 데이터 출력\n',data[mask]) # 1, 2번 행 출력
print('\n마스킹 역전된 데이터 출력\n',data[~mask]) 

[False  True  True False]

data 출력
 [[ 0.10262615  0.4829304 ]
 [-0.98899219  0.5027377 ]
 [-1.15482412  1.32245583]
 [-0.12013634 -0.56075364]]

마스킹된 데이터 출력
 [[-0.98899219  0.5027377 ]
 [-1.15482412  1.32245583]]

마스킹 역전된 데이터 출력
 [[ 0.10262615  0.4829304 ]
 [-0.12013634 -0.56075364]]


In [12]:
posit = data[data > 0]
print('양수 데이터 출력', '\n',posit)
#다중 조건
over1 = data[1][data[1] > 0]
print('두 번째 행의 양수 데이터 출력','\n',over1)

양수 데이터 출력 
 [0.10262615 0.4829304  0.5027377  1.32245583]
두 번째 행의 양수 데이터 출력 
 [0.5027377]


In [ ]:
a = np.arange(6)
b = a # 얕은 복사
print(a)
print(b is a)
b[0] = 10
print(a)

[0 1 2 3 4 5]
True
[10  1  2  3  4  5]


In [ ]:
a = np.arange(6)
c = a.copy() #깊은 복사
print(c is a) # 깊은 복사하면 서로 다르다고 판단함
c[0] = 20
print('A: ', a)
print('C: ', c)

False
A:  [0 1 2 3 4 5]
C:  [20  1  2  3  4  5]


In [ ]:
a = np.array([3, 2, 5, 1, 4])
print('원본\n',a)
print('정렬 후\n',np.sort(a)) # 정렬 해도 원본은 아직 변하지 않음
print('원본\n',a)
print('정렬한 인덱스\n',np.argsort(a))
a.sort( )
print('원본\n',a)

원본
 [3 2 5 1 4]
정렬 후
 [1 2 3 4 5]
원본
 [3 2 5 1 4]
정렬한 인덱스
 [3 1 0 4 2]
원본
 [1 2 3 4 5]


#3. 판다스 활용

In [16]:
#리스트로 시리즈 생성
import pandas as pd
a = pd.Series([1, 2, 3, 4])
print(a)
b = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
print(b)

0    1
1    2
2    3
3    4
dtype: int64
a    1
b    2
c    3
dtype: int64


In [17]:
#리스트로 데이터프레임 생성
list1 = list([['한빛', '남자', '20', '180'],
['한결', '남자', '21', '177'],
['한라', '여자', '20', '160']])
col_names = ['이름', '성별', '나이', '키']
pd.DataFrame(list1, columns=col_names)

이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

In [18]:
#딕셔너리로 데이터프레임 생성
dict1 = {'이름':{0:'한빛', 1:'한결', 2:'한라'},
'성별':{0:'남자', 1:'남자', 2:'여자'},
'나이':{0:'20', 1:'21', 2:'20'},
'키':{0:'180', 1:'177', 2:'160'}}
pd.DataFrame(dict1)


이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

In [19]:
#배열로 데이터프레임 생성
import numpy as np
#배열
arr1 = np.array([['한빛','남자', '20', '180'],
['한결','남자', '21', '177'],
['한라','여자', '20', '160']])
#열 이름 리스트
col_names = ['이름','성별','나이','키']
#데이터프레임 생성하기
pd.DataFrame(arr1, columns=col_names)


이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

In [20]:
# CSV 파일로 데이터프레임 생성
list1 = list([['허준호','남자','30','183'],
['이가원','여자','24','162'],
['배규민','남자','23','179'],
['고고림','남자','21','182'],
['이새봄','여자','28','160'],
['이보람','여자','26','163'],
['이루리','여자','24','157'],
['오다현','여자','24','172']])
col_names = ['이름','성별','나이','키']
df = pd.DataFrame(list1, columns=col_names)
df


이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [21]:
#데이터프레임을 CSV 파일로 저장
#디렉토리에 CSV 파일로 저장하기
df.to_csv('./file.csv', header=True, index=False,
encoding='utf-8')
#CSV 파일 읽기
df2 = pd.read_csv('./file.csv', sep=',')
df2


이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [22]:
#모든 열 이름 조회
df.columns

Index(['이름', '성별', '나이', '키'], dtype='object')

In [23]:
#데이터프레임 값 개수와 빈도수 확인
df.describe( )

이름  성별  나이    키
count     8   8   8    8
unique    8   2   6    8
top     허준호  여자  24  183
freq      1   5   3    1

In [24]:
#데이터프레임의 처음 세 행 검색
df.head(3)

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179

In [25]:
# 데이터프레임의 마지막 다섯 행 검색
df.tail( )

이름  성별  나이    키
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [26]:
#인덱스 기준으로 정렬
df.sort_index(axis=0).head( )

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160

In [27]:
#열 기준으로 정렬
#나이 열과 키 열을 기준으로 행을 정렬하기
df.sort_values(by=['나이', '키'], ascending=False).head( )

이름  성별  나이    키
0  허준호  남자  30  183
4  이새봄  여자  28  160
5  이보람  여자  26  163
7  오다현  여자  24  172
1  이가원  여자  24  162

In [28]:
#열 이름으로 데이터 조회
df[['이름', '키']].head( )

이름    키
0  허준호  183
1  이가원  162
2  배규민  179
3  고고림  182
4  이새봄  160

In [29]:
#인덱스로 데이터 조회
df.iloc[1:4, 0:3]

이름  성별  나이
1  이가원  여자  24
2  배규민  남자  23
3  고고림  남자  21

In [35]:
#조건식을 만족하는 데이터 조회(1)
# '키' column needs to be numeric for comparison
df['키'] = pd.to_numeric(df['키'])
df[df['키'] > 180].head()

이름  성별  나이    키
0  허준호  남자  30  183
3  고고림  남자  21  182

In [36]:
#조건식을 만족하는 데이터 조회(2)
list1 = list([['허준호', '남자', 30, 183],
['이가원', '여자', 24, 162],
['배규민', '남자', 23, 179],
['고고림', '남자', 21, 182],
['이새봄', '여자', 28, 160],
['이보람', '여자', 26, 163],
['이루리', '여자', 24, 157],
['오다현', '여자', 24, 172]])
col_names = ['이름', '성별', '나이', '키']
df = pd.DataFrame(list1, columns=col_names)
df[df['키'] > 180]

이름  성별  나이    키
0  허준호  남자  30  183
3  고고림  남자  21  182

In [ ]:
#리스트 요소와 일치하는 데이터 조회
df[df['나이'].isin([21, 23])]

이름  성별  나이    키
2  배규민  남자  23  179
3  고고림  남자  21  182

In [37]:
#두 조건식을 동시에 만족하는 데이터 조회
df[(df['성별'] == '여자') & (df['키'] > 160)]

이름  성별  나이    키
1  이가원  여자  24  162
5  이보람  여자  26  163
7  오다현  여자  24  172

In [ ]:
#두 조건식 중 하나 이상 만족하는 데이터 조회
df[(df['나이'] >= 28) | (df['성별'] == '남자')]

이름  성별  나이    키
0  허준호  남자  30  183
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160

In [ ]:
#특정 문자열을 포함하는 문자열 데이터 조회
df[df['이름'].str.contains('봄')]

이름  성별  나이    키
4  이새봄  여자  28  160

In [ ]:
#데이터프레임 통계 확인
df.describe( )

나이           키
count   8.000000    8.000000
mean   25.000000  169.750000
std     2.878492   10.552589
min    21.000000  157.000000
25%    23.750000  161.500000
50%    24.000000  167.500000
75%    26.500000  179.750000
max    30.000000  183.000000

In [ ]:
#인덱스로 조회한 데이터를 수정
df.loc[4,'키'] = df.loc[4,'키'] + 5 #4 번째 행의 '키' 인덱스에 5 더하기
df.loc[[4]]

이름  성별  나이    키
4  이새봄  여자  28  165

In [ ]:
#반복 연산자 사용
df.loc[1:3,'키'] = ['모름']*3 #iloc과 다르게 슬라이싱할 때 끝 값도 포함됨
df

/tmp/ipykernel_16177/3394123222.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['모름', '모름', '모름']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[1:3,'키'] = ['모름']*3


이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24   모름
2  배규민  남자  23   모름
3  고고림  남자  21   모름
4  이새봄  여자  28  165
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [ ]:
#인덱스 변경(1)
df.set_index('이름', inplace=True)
df.head(3)

성별  나이    키
이름              
허준호  남자  30  183
이가원  여자  24   모름
배규민  남자  23   모름

In [ ]:
#열 생성
df['보너스'] = df['나이'] * 10000
df.head(3)

성별  나이    키     보너스
이름                      
허준호  남자  30  183  300000
이가원  여자  24   모름  240000
배규민  남자  23   모름  230000

In [ ]:
#열 삭제
df.drop('보너스', axis=1, inplace=True)
df.head(3)

성별  나이    키
이름              
허준호  남자  30  183
이가원  여자  24   모름
배규민  남자  23   모름

In [ ]:
#인덱스 변경(2)
df.reset_index(inplace=True)
df.head(3)

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24   모름
2  배규민  남자  23   모름

In [ ]:
#데이터 치환
rep_cond = {'성별':{'남자':1, '여자':0}}
df2 = df.replace(rep_cond)
df2.head(3)

이름  성별  나이    키
0  허준호   1  30  183
1  이가원   0  24   모름
2  배규민   1  23   모름

In [ ]:
list1 = list([['허준호', '남자', 30, 183],
['이가원', '여자', 24, 162],
['배규민', '남자', 23, 179],
['고고림', '남자', 21, 182],
['이새봄', '여자', 28, 160],
['이보람', '여자', 26, 163],
['이루리', '여자', 24, 157],
['오다현', '여자', 24, 172]])
col_names = ['이름', '성별', '나이', '키']
df = pd.DataFrame(list1, columns=col_names)

In [ ]:
#데이터프레임의 값 연산
#성별 평균 키
mean_by_gender = df.groupby(by=['성별'], as_index=False)['키'].mean() # 성별로 그룹을 묶어서 키의 평균값을 구하는 과정
mean_by_gender.rename(columns={'키':'평균 키'}, inplace=True) 
#성별 키의 표준편차
std_by_gender = df.groupby(by=['성별'], as_index=False)['키'].std( ) # 성별로 그룹을 묶어서 키의 표준편차를 구하는 과정
std_by_gender.rename(columns = {'키':'키의 표준편차'}, inplace=True)
new_df = pd.merge(mean_by_gender, std_by_gender)
new_df

성별        평균 키   키의 표준편차
0  남자  181.333333  2.081666
1  여자  162.800000  5.630275